name: Bug report
description: Tell us what is not working.
title: "[Bug]: "
labels: [bug]
body:
  - type: textarea
    id: details
    attributes:
      label: What happened?
      description: Tell us what you expected and what happened instead. Please do not include private information.
    validations:
      required: true
  - type: input
    id: chrome
    attributes:
      label: Chrome version
