blank_issues_enabled: false
contact_links:
  - name: Install Block Notification
    url: https://chromewebstore.google.com/detail/block-notification/djljbdlfbneldoedlmdhmgnjhomfkoja?authuser=2&hl=ru
    about: Visit the Block Notification page on the Chrome Web Store.
