blank_issues_enabled: false
contact_links:
  - name: Установить расширение
    url: https://chromewebstore.google.com/detail/block-notification/djljbdlfbneldoedlmdhmgnjhomfkoja?authuser=2&hl=ru
    about: Страница Block Notification в Chrome Web Store.
