name: Feature request
description: Suggest an improvement for Block Notification.
title: "[Idea]: "
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: Your idea
    validations:
      required: true
